### ISSUE TITLE
Get Object Properties should reflect current object properties

### ISSUE THREAD

**Issue by richardaubin** [DominicBeer/Objectivism#4]
Not sure if it's supposed to work that way or not, but I figured if I change the property name of the original object, and then hit update on that, then on Update on the GOP component the property names should change.

Doing an explode at this point adds the new property name, but keeps the old one, forcing a manual delete of the original property in order to reflect the current object state.

![image](https://user-images.githubusercontent.com/37956997/209847812-49472b58-40ef-480f-879e-5f205dbf8006.png)
![image](https://user-images.githubusercontent.com/37956997/209847849-0075d316-5b00-4357-8e20-399391c09849.png)

**Comment by DominicBeer** [comment]
The "Update Object" button is only there to force that object to recalculate after a text change, not update the property name across the board. The issue with trying to propagate the name changes is that there are a lot of edge cases to consider. I might instead consider a "Find and Replace" feature for the property names, which just finds all the instances of that property name on the canvas changes them. Its then clear to the user that a large scale change is going to occur across the canvas.

**Comment by richardaubin** [comment]
That sounds like a viable alternative.

**Comment by DominicBeer** [comment]
Richard, fyi I have just released a new version of the plugin with a prototype "Find and Replace" feature. Right click on a property and hit "Change Property Name" and it will bring up a control

**Comment by richardaubin** [comment]
This can be closed.  I've checked and am now using this feature.
